#----------------------------------------------------------------------
# This file was generated by /usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/tools/img2py.py
# as shown in http://www.blog.pythonlibrary.org/2008/05/23/wxpython-embedding-an-image-in-your-title-bar/
from wx.lib.embeddedimage import PyEmbeddedImage

icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAGtJ"
    "REFUOI2tUVsOwCAIa3f/O7OPYcSJCG79ITHQl0QJIs8kAQgAXDWCzqSTp8eNIMMw2zbyrETI"
    "2BbpitOx954q8b/CPIR5XvLu7ipC1fZQ3tZ25GBQVtaQTAloI5babsupwlYOPv2zFT7CDWyj"
    "JgFLeHL+AAAAAElFTkSuQmCC")

